### ISSUE TITLE
Datasheet erstellen

### ISSUE THREAD

**Issue by mxzinke** [mxzinke/PM_Spiel_DHBW18C#2]
Jedes der Teams muss ein eigenes Datasheet schreiben. Bitte verwendet die Vorlage und pusht sie ins Repo. Verantwortliche das dies mit Richtigkeit umgesetzt wird, ist der _Teamleiter_.

**Comment by lisaangermund** [comment]
[DatasheetTeam1_07.05.2019.docx](https://github.com/mxzinke/PM_Spiel_DHBW18C/files/3158325/DatasheetTeam1_07.05.2019.docx)
Erstes Datasheet vom 07. Mai 2019
Letztes Update: 08. Mai 2019
