### ISSUE TITLE
Teamabmachung

### ISSUE THREAD

**Issue by mxzinke** [mxzinke/PM_Spiel_DHBW18C#8]
Im Projekt benötigen wir für ALLE Teams eine einheitliche Teamabmachung, die definiert wie sich Teammitglieder im Team zu verhalten haben.

Folgende Punkte stehen bereits ein der Abmachung:
* wir kommen pünktlich und vorbereitet zur Besprechung
* wir achten die anderen Teammitglieder
* wir akzeptieren Teamentscheidungen/-abstimmungen
* wir sind bereit Überstunden zu machen bzw. in unseren Freizeit dran weiter zu arbeiten
* wir dokumentieren den Zeitaufwand akribisch
* wir helfen uns gegenseitig & sprechen uns untereinander ab
* wir verfassen jegliche wichtigen Dokumente auf *Deutsch* (Team-eigene Festlegung ausgeschlossen)
* wir werden alle Aufgaben als Issues im Git-Repository eingetragen, um den Projektfortschritt verfolgen (Team-eigene Repo's eingeschlossen) zu können
* wir arbeiten nur nach den definierte Anforderungen und betreiben kein Over-Engineering

Nun ist die Frage, welche Ideen habt ihr noch? Seid ihr mit allen Abmachungen einverstanden, oder besteht Änderungsbedarf?

**Comment by d4n1e** [comment]
•	wir arbeiten nach den definierte Anforderungen für die gemeinsame Vision des Projekterfolges
•	wir tragen alle Aufgaben als Issues im Git-Repository ein, um den Projektfortschritt verfolgen (Team-eigene Repo's eingeschlossen) zu können
•	wir verfassen jegliche wichtigen Dokumente auf Deutsch (Team-eigene Festlegung ausgeschlossen)
•	wir achten die anderen Projektmitglieder für eine angenehme und respektvolle Arbeitsatmosphäre
•	wir kommunizieren ehrlich und transparent
•	wir helfen uns gegenseitig und suchen bei Kritik die konstiktive Lösung
•	wir akzeptieren Teamentscheidungen/-abstimmungen
•	wir kommen pünktlich und vorbereitet zur Besprechung
•	wir sind bereit Überstunden zu machen bzw. in unseren Freizeit dran weiter zu arbeiten
•	wir dokumentieren den Zeitaufwand akribisch
